# Generated by Django 3.0.8 on 2020-07-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='id',
        ),
        migrations.AlterField(
            model_name='branch',
            name='ifsc',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
